<?php $this->headTitle('Home'); ?>

<!-- TODO: implement front end -->
<h1>Create a booking</h1>
<div class="row">
    <?php $this->headScript()->captureStart() ?>
    var action = '<?php echo $this->baseUrl ?>';
    $('foo_form').action = action;
    <?php $this->headScript()->captureEnd() ?>
    <!--  TODO: probably can be done less hacky  -->
    <form action="<?=$this->url('api.booking', [], [
        'handle' => 'create',
    ])?>" method="POST">
        <div class="form-group">
            <label for="user">User Name</label>
            <input type="text" class="form-control" id="user">
            <label for="reason">Reason</label>
            <input type="text" class="form-control" id="reason">
            <label for="start_date">Start Date</label>
            <input type="text" class="form-control" id="start_date">
            <label for="end_date">End Date</label>
            <input type="text" class="form-control" id="end_date">
            <label for="booking_id">Booking Id (update only)</label>
            <input type="text" class="form-control" id="booking_id">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>